### ISSUE TITLE
Wrong value for 250 Ohms with diode trickle charger.  

### ISSUE THREAD

**Issue by RudyFiero** [duarterr/Arduino-DS1390-SPI#1]
In DS1390_SPI.h

You use **0x29** but the correct value is **0xA9**. See page 18 & 18 of the data sheet. 
http://www.farnell.com/datasheets/1918612.pdf

Top 4 bits must be 1010 for charger to be enabled. You have this correct for all the other options.

#define DS1390_TCH_250_D        0x29  // 250 Ohms with diode

change to

#define DS1390_TCH_250_D        0xA9  // 250 Ohms with diode

**Comment by duarterr** [comment]
You are correct!

Thanks for sharing. I'll correct the file
